spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  profiles:
    active: local
    group:
      local: db
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.boot.actuate: DEBUG
    org.apache.catalina: DEBUG
cloud:
  aws:
    s3:
      bucket: ${BUCKET_NAME}
    region :
      static : ap-northeast-2
    stack:
      auto: false
    credentials:
      accessKey: ${ACCESS_KEY}
      secretKey: ${SECRET_KEY}